---
- name: Add haproxy repo key
  shell: curl https://haproxy.debian.net/bernat.debian.org.gpg | gpg --dearmor > /usr/share/keyrings/haproxy.debian.net.gpg 
  
- name: Add haproxy repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/haproxy.debian.net.gpg] http://haproxy.debian.net bookworm-backports-2.8 main"
    state: present
    filename: haproxy
    update_cache: true
  when: ansible_distribution == "Debian"

- name: Add haproxy repository
  apt_repository:
    repo: ppa:vbernat/haproxy-2.8.\*
    state: present
    filename: haproxy
    update_cache: true
  when: ansible_distribution == "Ubuntu"
    
#- name: Install haproxy packages
#  apt:
#    name: 'haproxy=2.8.\*'
#    state: latest
    
- name: generate haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
