---
- hosts: all
#  user: ubuntu
  become: true
  roles:
    - common

- hosts: all
  become: true
  tasks:
    - name: run firewall
      include_role:
        name: firewall
      when: firewall_enabled|bool == true

- hosts:
    - master
    - workers
  roles:
#    - docker
    - k8s
    - crio

- hosts: lb
  become: true
  roles:
    - lb
