---
- hosts: all
#  user: ubuntu
  become: false
  roles:
  - common

- hosts: all
  become: false
  tasks:
  - name: run firewall
    include_role:
      name: firewall
    when: firewall_enabled|bool == true

- hosts:
  - master
  - workers
  become: false
  roles:
  - k8s

- hosts:
  - master
  - workers
  become: false
  roles:
  - containerd
  tags:
  - containerd

- hosts:
  - master
  - workers
  become: false
  roles:
  - crio
  tags:
  - crio

- hosts: lb
  become: false
  roles:
  - haproxy
