---
- name: install kubernetes required software
  block:
    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes apt signing key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: '0644'

    - name: Add Kubernetes apt signing key
      ansible.builtin.shell: |
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
        args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Remove temporary key file
      ansible.builtin.file:
        path: /tmp/kubernetes-release.key
        state: absent

    - name: add k8s repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ VERSION }}/deb/ /"
        filename: k8s
        state: present

    - name: install k8s related software
      apt:
        name: ['kubeadm={{ K8S_VERSION }}', 'kubelet={{ K8S_VERSION }}', 'kubectl={{ K8S_VERSION }}', 'ipset', 'ipvsadm']
        state: present
        update_cache: true
      notify:
        - start kubelet

    - name: install ipvs mode modules
      modprobe:
        name: '{{ item }}'
        state: present
      loop:
        - ip_vs
        - ip_vs_rr
        - ip_vs_wrr
        - ip_vs_sh
        - nf_conntrack

    - name: persist ipvs modules
      copy:
        src: ipvs.conf
        dest: /etc/modules-load.d/ipvs.conf

    - name: get the status of kubeadm package
      shell: dpkg --get-selections | grep kubeadm
      register: pkg_status

    - debug:
        var: pkg_status

    - name: mark hold on apps to prevent upgrades
      shell: apt-mark hold '{{ item }}'
      with_items:
        - kubeadm
        - kubelet
        - kubectl
      when:
        - not pkg_status.stdout is search("hold") 
